services:
  web:
    build: .
    image: madrasglocal:latest
    container_name: madrasglocal-web
    restart: always
    expose:
      - "80"
    networks:
      - npm-net

networks:
  npm-net:
    external: true
